server:
  port: 8083

spring:
  application:
    name: streaming-service

  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
    username: postgres.nnggmlcilcntpikhdtdr
    password: 2dL!h7bwQ6#kCb@
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

supabase:
  project-ref: nnggmlcilcntpikhdtdr
  access-key: e70caba84aea728c7faec7dc41921674
  secret-key: 453ec35ccde941ec9588f134340ce15790e920bb8851955f17e39a30df4a32a9

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
